input_stream: "input1"
input_stream: "input2"
input_stream: "input_tick"

node {
   calculator: "PacketClonerCalculator"
   input_stream: "input1"
   input_stream: "input2"
   input_stream: "input_tick"
   output_stream: "output1"
   output_stream: "output2"
   node_options: {
    [type.googleapis.com/mediapipe.PacketClonerCalculatorOptions] {
        output_packets_only_when_all_inputs_received: true
    }
   }
 }